name: 'Deployment Status'
description: 'Automatically updates the most recent deployment with proper status'

inputs:
  deployment_id:
    description: 'Deployment ID of previous deployment to update'
    required: false

  token:
    description: GITHUB_TOKEN to access the GitHub API if the repository is private
    required: false

  step:
    description: One of 'start', 'finish', 'deactivate-env', or 'delete-env'
    required: true

  status:
    description: The deployment status (for `finish` only)
    required: false
    default: ${{ job.status }}

  env_url:
    required: false
    description: The environment URL (for `finish` only)

outputs:
  deployment_id:
    description: 'Deployment ID of deployment updated or created'
    value: ${{ steps.deployment.outputs.deployment_id }}
  environment:
    description: 'Deployment environment'
    value: ${{ steps.environment.outputs.variable }}

runs:
  using: 'composite'
  steps:
    - name: Get Ref
      id: ref
      uses: alehechka-io/kubernetes-actions/get-ref@main

    - name: Get Environment
      id: environment
      uses: alehechka-io/kubernetes-actions/determine-environment@main
      with:
        token: ${{ inputs.token }}
        production_variable: 'production'
        staging_variable: 'staging'
        development_variable: '${{ steps.ref.outputs.name }}'

    - name: Deployment Status
      id: deployment
      uses: bobheadxi/deployments@v1
      with:
        token: ${{ inputs.token }}
        step: ${{ inputs.step }}
        env: ${{ steps.environment.outputs.variable }}
        env_url: ${{ inputs.env_url }}
        ref: ${{ steps.ref.outputs.name }}
        deployment_id: ${{ inputs.deployment_id }}
        status: ${{ inputs.status }}
        auto_inactive: true
