name: 'Deployment Status'
description: 'Automatically updates the most recent deployment with proper status'

inputs:
  deployment_id:
    description: 'Deployment ID of previous deployment to update'
    required: false

  environment:
    description: 'Environment of Deployment'
    required: false
    default: development

  token:
    description: GITHUB_TOKEN to access the GitHub API if the repository is private
    required: false

  step:
    description: One of 'start', 'finish', 'deactivate-env', or 'delete-env'
    required: true

  status:
    description: The deployment status (for `finish` only)
    required: false
    default: ${{ job.status }}

  env_url:
    required: false
    description: The environment URL (for `finish` only)

outputs:
  deployment_id:
    description: 'Deployment ID of deployment updated or created'
    value: ${{ steps.deployment.outputs.id }}

runs:
  using: 'composite'
  steps:
    - name: Get Ref
      id: ref
      uses: alehechka-io/kubernetes-actions/get-ref@main

    - name: Find previous deployment
      id: deployment
      run: |
        if [[ -n "${{ inputs.deployment_id }}" ]]; then
          echo "::set-output name=id::${{ inputs.deployment_id }}"

        else
          PREV_DEPLOY=$(gh api "/repos/${{ github.repository }}/deployments?ref=${{ steps.ref.outputs.name }}&per_page=1&environment=${{ inputs.environment }}" | jq '.[0].id // empty')
          echo "::set-output name=id::$PREV_DEPLOY"

        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Deployment Status
      uses: bobheadxi/deployments@v1
      with:
        token: ${{ inputs.token }}
        step: ${{ inputs.step }}
        env: ${{ inputs.environment }}
        env_url: ${{ inputs.env_url }}
        ref: ${{ steps.ref.outputs.name }}
        deployment_id: ${{ steps.deployment.outputs.id }}
        status: ${{ inputs.status }}
        auto_inactive: ${{ inputs.environment == 'staging' || inputs.environment == 'production' }}
