name: 'Get Short Sha'
description: 'Truncates the commit sha to the first 7 digits'

outputs:
  short_sha:
    description: 'Shortened Sha'
    value: ${{ steps.short.outputs.sha }}

runs:
  using: 'composite'
  steps:
    - name: Short Sha
      id: short
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          SHA="${{ github.event.pull_request.head.sha }}"

        else
          SHA="${{ github.sha }}"
          
        fi

        echo "sha=${SHA::7}" >> $GITHUB_OUTPUT
      shell: bash
