name: Create feature branch Namespace
description: Creates a feature branch Namespace with proper labels to allow replication of resources

outputs:
  namespace:
    description: Prepare namespace
    value: ${{ steps.namespace.outputs.name }}

runs:
  using: composite
  steps:
    - name: Get Ref
      id: ref
      uses: alehechka-io/kubernetes-actions/get-ref@main

    - name: Prepare Namespace Name
      id: namespace
      run: ${{ github.action_path }}/scripts/clean_variable.sh ${{ steps.ref.outputs.name }} name
      shell: bash

    - name: Get Existing Namespace
      id: namespace-json
      run: ${{ github.action_path }}/scripts/get_namespace.sh ${{ steps.namespace.outputs.name }} value
      shell: bash

    - name: Create Feature Namespace
      if: steps.namespace-json.outputs.value == ''
      run: cat ${{ github.action_path }}/k8s/feature.namespace.yaml | envsubst | kubectl apply -f -
      env:
        NAMESPACE: ${{ steps.namespace.outputs.name }}
        REF_NAME: ${{ steps.ref.outputs.name }}
      shell: bash
