name: Create feature branch Namespace
description: Creates a feature branch Namespace with proper labels to allow replication of resources

inputs:
  namespace:
    description: 'Namespace to deploy Helm chart. If not provided, will be calculated from action trigger'
    required: false

outputs:
  namespace:
    description: Prepared namespace
    value: ${{ steps.namespace.outputs.variable }}

runs:
  using: composite
  steps:
    - name: Get Ref
      id: ref
      uses: alehechka-io/kubernetes-actions/get-ref@main
      with:
        custom_ref: ${{ inputs.namespace }}

    - name: Prepare Namespace Name
      id: namespace
      uses: alehechka-io/kubernetes-actions/clean-variable@main
      with:
        variable: ${{ steps.ref.outputs.name }}

    - name: Get Existing Namespace
      id: namespace-json
      run: ${{ github.action_path }}/scripts/get_namespace.sh ${{ steps.namespace.outputs.variable }} value
      shell: bash

    - name: Create Feature Namespace
      if: steps.namespace-json.outputs.value == ''
      run: cat ${{ github.action_path }}/k8s/feature.namespace.yaml | envsubst | kubectl apply -f -
      env:
        NAMESPACE: ${{ steps.namespace.outputs.variable }}
        REF_NAME: ${{ steps.ref.outputs.name }}
      shell: bash
