name: Create feature branch Namespace
description: Creates a feature branch Namespace with proper labels to allow replication of resources

outputs:
  namespace:
    description: Prepare namespace
    value: ${{ steps.namespace.outputs.name }}

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - name: Check for existing namespace
      id: namespace
      run: ./action/scripts/clean_variable.sh ${{ github.ref_name }} name

    - name: Get Existing Namespace
      id: namespace-json
      run: ./action/scripts/get-namespace.sh ${{ steps.namespace.outputs.name }} value

    - name: Create Feature Namespace
      if: steps.namespace-json.outputs.value == ''
      run: cat ./action/.github/actions/create-feature-namespace/feature.namespace.yaml | envsubst | kubectl apply -f -
      env:
        - NAMESPACE: ${{ steps.namespace.outputs.name }}
