name: Create feature branch Namespace
description: Creates a feature branch Namespace with proper labels to allow replication of resources

outputs:
  namespace:
    description: Prepare namespace
    value: ${{ steps.namespace.outputs.name }}

runs:
  using: composite
  steps:
    - name: Get Ref
      id: ref
      uses: ./action/.github/actions/get-ref

    - name: Check for existing namespace
      id: namespace
      run: ./action/scripts/clean_variable.sh ${{ steps.ref.outputs.name }} name
      shell: bash

    - name: Get Existing Namespace
      id: namespace-json
      run: ./action/scripts/get_namespace.sh ${{ steps.namespace.outputs.name }} value
      shell: bash

    - name: Create Feature Namespace
      if: steps.namespace-json.outputs.value == ''
      run: cat ./action/.github/actions/create-feature-namespace/k8s/feature.namespace.yaml | envsubst | kubectl apply -f -
      env:
        NAMESPACE: ${{ steps.namespace.outputs.name }}
      shell: bash
