name: Test determine-environment
on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
  pull_request:
    paths:
      - 'determine-environment/**/*'
      - '.github/workflows/test-determine-environment.yaml'

jobs:
  test-determine-environment:
    name: Test determine environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine Environment
        id: environment
        uses: ./determine-environment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Environment: ${{ steps.environment.outputs.environment }}'
        run: echo "${{ steps.environment.outputs.environment }}"
